# Generated by Django 4.0.2 on 2022-02-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('genre', models.CharField(max_length=20)),
                ('keyword', models.CharField(max_length=20)),
                ('theme', models.CharField(max_length=20)),
                ('game_modes', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=20)),
                ('platforms', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
