# Generated by Django 4.0.2 on 2022-02-23 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0002_user_delete_greeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3)),
                ('genre', models.CharField(max_length=20)),
                ('keyword', models.CharField(max_length=20)),
                ('theme', models.CharField(max_length=20)),
                ('game_modes', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=20)),
                ('platforms', models.CharField(max_length=20)),
                ('userName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
