# Generated by Django 4.0.3 on 2022-03-09 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_alter_entry_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='userName',
            new_name='user',
        ),
    ]
