# Generated by Django 4.0.3 on 2022-03-22 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_rec_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rec',
            name='rating',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='rec',
            name='games',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rec',
            name='timestamp',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
