# Generated by Django 4.0.3 on 2022-03-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_rec_rating_alter_rec_games_alter_rec_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='rating',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
