# Generated by Django 4.0.3 on 2022-03-23 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0011_alter_rec_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
